-- TRUNCATE TABLE Contrat RESTART IDENTITY CASCADE;
TRUNCATE TABLE DetailDevis RESTART IDENTITY CASCADE;
TRUNCATE TABLE Devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE DemandeStatut RESTART IDENTITY CASCADE;
TRUNCATE TABLE Demande RESTART IDENTITY CASCADE;
TRUNCATE TABLE TypeDevis RESTART IDENTITY CASCADE;
TRUNCATE TABLE Statut RESTART IDENTITY CASCADE;
TRUNCATE TABLE Lieu RESTART IDENTITY CASCADE;
TRUNCATE TABLE Client RESTART IDENTITY CASCADE;