TRUNCATE TABLE notes RESTART IDENTITY;
TRUNCATE TABLE parametres RESTART IDENTITY;
TRUNCATE TABLE regles RESTART IDENTITY;
TRUNCATE TABLE matieres RESTART IDENTITY;
TRUNCATE TABLE operateur RESTART IDENTITY;
TRUNCATE TABLE correcteurs RESTART IDENTITY;
TRUNCATE TABLE eleves RESTART IDENTITY;