DROP VIEW IF EXISTS notefinales;

DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS parametres;
DROP TABLE IF EXISTS regles;
DROP TABLE IF EXISTS matieres;
DROP TABLE IF EXISTS operateur;
DROP TABLE IF EXISTS correcteurs;
DROP TABLE IF EXISTS eleves;