-- DROP TABLE IF EXISTS Contrat CASCADE;
DROP TABLE IF EXISTS DetailDevis CASCADE;
DROP TABLE IF EXISTS Devis CASCADE;
DROP TABLE IF EXISTS DemandeStatut CASCADE;
DROP TABLE IF EXISTS Demande CASCADE;
DROP TABLE IF EXISTS TypeDevis CASCADE;
DROP TABLE IF EXISTS Statut CASCADE;
DROP TABLE IF EXISTS Lieu CASCADE;
DROP TABLE IF EXISTS Client CASCADE;